platform: linux
image_resource:
  type: registry-image
  source:
    # the docker image to use
    repository: mattcl/aoc-ci-bencher
    tag: latest

inputs:
  # this repository will be provided to the task in the registry-image as a
  # directory named `repo`
  - name: ci
  - name: repo

outputs:
  - name: repo

caches:
  # yeah, I'm not sure how I feel about caching the registry like this,
  # but concourse only allows relative paths instead of absolute ones
  - path: ../../../root/.cabal/store

  # cache the target folder to speed up builds
  - path: repo/dist-newstyle

run:
  # we execute the build script in the context of the this in the aoc-python
  # container, which contains py 3.12 and poetry, among other things.
  dir: repo
  path: ci/scripts/build.sh
