platform: linux
image_resource:
  type: registry-image
  source:
    repository: oven/bun
    tag: debian

inputs:
  - name: repo

outputs:
  - name: release

run:
  dir: repo
  path: ci/scripts/build.sh
