[general]
pipeline_url = "http://ci.papercode.net:8080/teams/main/pipelines/aoc2023"
year = 2023
timeout = 30

[participants.mattcl]
username = "mattcl"
repo = "https://github.com/mattcl/aoc2023"
location = "mattcl"
language = "rust"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "mattcl-aoc run"
is_solver = true

[participants.mattcl-py]
username = "mattcl-py"
repo = "https://github.com/mattcl/aoc2023-py"
location = "mattcl-py"
language = "python"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "mattcl-aoc-py-bench"
# no point in collecting identical inputs from this project
skip_inputs = true

[participants.chancalan]
username = "chancalan"
repo = "https://github.com/chancalan/aoc2023"
location = "chancalan"
language = "python"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "chancalan-aoc-bench"

[participants.lanjian]
username = "lanjian"
repo = "https://github.com/lanjian/aoc-2023"
location = "lanjian"
language = "rust"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "lanjian-aoc run"

[participants.pting]
username = "pting"
repo = "https://github.com/pting/aoc2023"
location = "pting"
language = "python"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "pting-aoc-bench run"

[participants.kcen]
username = "kcen"
repo = "https://github.com/kcen/aoc2023"
location = "kcen"
language = "python"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "kcen-aoc-bench run"

[participants.aspidites]
username = "aspidites"
repo = "https://github.com/aspidites/aoc2023"
location = "aspidites"
language = "haskell"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "aspidites-aoc --json"

[participants.mikofo]
username = "mikofo"
repo = "https://github.com/mikofo/advent-of-code-2023"
location = "mikofo"
language = "javascript"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "yarn -s --cwd /mikofo start"
