[general]
pipeline_url = "http://ci.papercode.net:8080/teams/main/pipelines/aoc2024"
year = 2024
timeout = 30

[participants.mattcl]
username = "mattcl"
repo = "https://github.com/mattcl/aoc2024"
location = "mattcl"
language = "rust"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "mattcl-aoc run"
is_solver = true

[participants.mattcl-py]
username = "mattcl-py"
repo = "https://github.com/mattcl/aoc2024-py"
location = "mattcl-py"
language = "python"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "mattcl-aoc-py-bench"
# no point in collecting identical inputs from this project
skip_inputs = true

[participants.lanjian]
username = "lanjian"
repo = "https://github.com/lanjian/aoc-2024"
location = "lanjian"
language = "rust"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "lanjian-aoc run"

[participants.kcen]
username = "kcen"
repo = "https://github.com/kcen/aoc2024"
location = "kcen"
language = "nim"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "kcen-aoc"

[participants.mikofo]
username = "mikofo"
repo = "https://github.com/mikofo/aoc2024"
location = "mikofo"
language = "python"
input_cmd = "ci/scripts/input_path.sh"
entrypoint = "mikofo-aoc-py-bench"
