resources:
  - name: mattcl
    type: git
    icon: github
    source:
      uri: https://github.com/mattcl/aoc2021.git
  - name: lanjian
    type: git
    icon: github
    source:
      uri: https://github.com/LanJian/aoc-2021.git
  - name: nathanwang2
    type: git
    icon: github
    source:
      uri: https://github.com/NathanWang2/adventOfCode2021.git
  - name: ci
    type: git
    icon: github
    source:
      uri: https://github.com/mattcl/aoc-ci-bencher.git
  - name: aoc-inputs
    type: git
    icon: github
    source:
      uri: git@github.com:mattcl/aoc-aggregated-inputs.git
      branch: master
      private_key: ((aoc-inputs.deploy_key))

jobs:
  - name: collect-inputs
    public: true
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: aoc-inputs
          trigger: false
        - get: mattcl
          trigger: true
        - get: lanjian
          trigger: true
        - get: nathanwang2
          trigger: true
      - task: collect
        file: ci/tasks/collect-inputs.yml
      - put: aoc-inputs
        params: {repository: modified-aoc-inputs}

  - name: mattcl
    public: true
    plan:
      - get: ci
        trigger: false
      - get: repo
        resource: mattcl
        trigger: true
      - task: run-all
        file: ci/tasks/generic-rust.yml

  - name: lanjian
    public: true
    plan:
      - get: ci
        trigger: false
      - get: repo
        resource: lanjian
        trigger: true
      - task: run-all
        file: ci/tasks/generic-rust.yml

  - name: nathanwang2
    public: true
    plan:
      - get: ci
        trigger: false
      - get: repo
        resource: nathanwang2
        trigger: true
      - task: run-all
        file: ci/tasks/generic-python.yml
        vars:
          script: ci/scripts/nw-python
