resources:
  - name: mattcl
    type: git
    icon: github
    source:
      uri: https://github.com/mattcl/aoc2022.git

  - name: ci
    type: git
    icon: github
    source:
      uri: https://github.com/mattcl/aoc-ci-bencher.git

  - name: aoc-inputs
    type: git
    icon: github
    source:
      uri: https://github.com/mattcl/aoc-aggregated-inputs.git
      branch: master
      ignore_paths:
        - '**/application-benches.md'
        - '**/solutions.md'

  # this is the same repository as the aoc-inputs resource, but this one allows
  # writes (this is done to avoid new concourse version detection for ignored
  # paths) see https://github.com/concourse/git-resource
  - name: aoc-inputs-write
    type: git
    icon: github
    source:
      uri: git@github.com:mattcl/aoc-aggregated-inputs.git
      branch: master
      private_key: ((aoc-inputs.deploy_key))

jobs:
  - name: solve-inputs
    public: true
    serial_groups: [collection]
    build_log_retention:
      builds: 50
    plan:
      - in_parallel:
        - get: ci
          trigger: false
        - get: aoc-inputs
          trigger: true
        - get: mattcl
          trigger: false
      - task: build-solver
        file: ci/tasks/build-solver.yml
        input_mapping:
          repo: mattcl
      - task: solve
        file: ci/tasks/solve-inputs.yml
      - put: aoc-inputs-write
        params:
          repository: modified-aoc-inputs
          rebase: true
