platform: linux
image_resource:
  type: registry-image
  source:
    repository: bitnami/git
    tag: latest

inputs:
  - name: ci
  - name: repo

outputs:
  - name: release

run:
  path: ci/2024/scripts/kcen-package.sh
