platform: linux
image_resource:
  type: registry-image
  source:
    repository: mattcl/aoc-ci-bencher
    tag: latest

inputs:
  - name: ci
  - name: repo

outputs:
  - name: repo

run:
  dir: repo
  path: ../ci/2024/scripts/kcen-build.sh
