platform: linux
image_resource:
  type: registry-image
  source:
    repository: mattcl/py-ghc
    tag: 3.10.8-9.2.4

inputs:
  - name: ci
  - name: repo

caches:
  # cache the target folder to speed up builds
  - path: repo/dist-newstyle

outputs:
  - name: solver

run:
  path: ci/scripts/build-aspidites-solver
