platform: linux
image_resource:
  type: registry-image
  source:
    repository: alpine/git
    tag: latest

inputs:
  - name: ci
  - name: aoc-inputs
  - name: mattcl
  - name: lanjian
  - name: nathanwang2

outputs:
  - name: modified-aoc-inputs

run:
  dir: repo
  path: ci/scripts/extract-inputs
