platform: linux
image_resource:
  type: registry-image
  source:
    repository: rust
    tag: 1.56

inputs:
  - name: mattcl

caches:
  # yeah, I'm not sure how I feel about caching the registry like this,
  # but concourse only allows relative paths instead of absolute ones
  - path: ../../../usr/local/cargo/registry

  # cache the target folder to speed up builds
  - path: mattcl/target

outputs:
  - name: mattcl-examples
    path: mattcl/aoc2021-mattcl.tar.gz

run:
  path: /bin/sh
  args:
    - "-c"
    - |
      cd mattcl
      cargo build --release --examples
      ./scripts/package-examples
