platform: linux
image_resource:
  type: registry-image
  source:
    repository: python
    tag: 3.9

inputs:
  - name: repo

run:
  dir: repo
  path: /bin/sh
  args:
    - "-c"
    - |
      for d in $(find . -maxdepth 1 -type d -regextype sed -regex ".*/day.*" -exec basename {} \;)
      do
        cd $d
        echo "attempting to run $d"
        ../ci/tools/hyperfine/hyperfine -w 3 'python *.py'
        cd ../
      done
